export {default as Education} from './Education'
export {default as Skills} from './Skills'
export {default as CertiPapers} from './CertiPapers'
export {default as POR} from './POR'
export {default as Projects} from './Projects'
export {default as WorkExperience} from './WorkExperience'
