const BlogActions = {
  GET_ALL_BLOGS_FROM_DB: "GET_ALL_BLOGS_FROM_DB",
  SET_ALL_BLOGS_TO_STORE: "SET_ALL_BLOGS_TO_STORE",
  SAVE_LIKE_TO_DB:"SAVE_LIKE_TO_DB",
  SAVE_LIKE_TO_STORE:"SAVE_LIKE_TO_STORE",
  SAVE_BLOG_TO_DB:"SAVE_BLOG_TO_DB",
  SAVE_BLOG_TO_STORE:"SAVE_BLOG_TO_STORE",
  DELETE_BLOG_FROM_DB:"DELETE_BLOG_FROM_DB",
  DELETE_BLOG_FROM_STORE:"DELETE_BLOG_FROM_STORE",
  // ADD_ONE_BLOG_TO_DB: "SEND_ONE_BLOG_DB",
  // GET_ALL_BLOGS_OF_USER_DB: "GET_ALL_BLOGS_OF_USER_DB",
  // GET_ONE_BLOG_OF_USER_DB: "GET_ONE_BLOG_OF_USER_DB"
};

export default BlogActions;
