const UserActions = {
  REGISTER_USER_TO_DB: "REGISTER_USER_TO_DB",
  GET_ONE_USER_FROM_DB: "GET_ONE_USER_FROM_DB",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_RESPONSE:"LOGIN_USER_RESPONSE",
  UPDATE_USER:"UPDATE_USER",
  UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
  LOGOUT_USER:"LOGOUT_USER",
  RELOGIN_USER_USING_TOKEN:"RELOGIN_USER_USING_TOKEN",
  UPDATE_USER_TO_DB:"UPDATE_USER_TO_DB",
  UPDATE_USER_TO_STORE:"UPDATE_USER_TO_STORE",
  RESET_PASSWORD:"RESET_PASSWORD",
};

export default UserActions;
