const UserActions = {
  REGISTER_USER_TO_DB: "REGISTER_USER_TO_DB",
  GET_ONE_USER_FROM_DB: "GET_ONE_USER_FROM_DB",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_RESPONSE:"LOGIN_USER_RESPONSE",
  UPDATE_USER:"UPDATE_USER",
  UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
};

export default UserActions;
